version: '3.1'

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - ./init.db/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  postgresdb:
    image: postgres:11
    container_name: postgresdb
    environment:
      POSTGRES_DB: sakila
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.db/postgres:/docker-entrypoint-initdb.d