version: '3.1'

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - ./init.db/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306